from typing import Protocol

from CapacityEngine.Domain.Entities import AlertThreshold, Baseline, CapacityKpi, ForecastResult, MetricSample, Recommendation, RiskAssessment, Service, ServiceResourceMap


class CatalogRepository(Protocol):
    def LoadServices(self) -> list[Service]: ...
    def LoadServiceResourceMaps(self) -> list[ServiceResourceMap]: ...


class MetricRepository(Protocol):
    def LoadSamples(self) -> list[MetricSample]: ...
    def LoadThresholds(self) -> list[AlertThreshold]: ...
    def LoadBaselines(self) -> list[Baseline]: ...


class CapacityOutputRepository(Protocol):
    def SaveKpis(self, Kpis: list[CapacityKpi]) -> None: ...
    def SaveForecasts(self, Forecasts: list[ForecastResult]) -> None: ...
    def SaveRisks(self, Risks: list[RiskAssessment]) -> None: ...
    def SaveRecommendations(self, Recommendations: list[Recommendation]) -> None: ...
