apiVersion: 1
deleteDatasources:
  - name: VictoriaMetrics
    orgId: 1
  - name: CapacityPostgreSQL
    orgId: 1
prune: true
datasources:
  - name: VictoriaMetrics
    uid: VictoriaMetrics
    type: prometheus
    access: proxy
    orgId: 1
    url: http://capacity-performance-victoriametrics:8428
    isDefault: true
    version: 2
    editable: false
  - name: CapacityPostgreSQL
    uid: CapacityPostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: capacity-performance-postgresql:5432
    database: capacity
    user: capacity
    jsonData:
      database: capacity
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: capacity
    version: 3
    editable: false
