UserParameter=capacity.enterprise.fact[*],/bin/sh /usr/local/bin/ReadEnterpriseFact.sh "$1" "$2"
UserParameter=capacity.platform.status[*],/bin/sh /usr/local/bin/ReadPlatformStatus.sh "$1"
UserParameter=capacity.platform.metric[*],/bin/sh /usr/local/bin/ReadPlatformMetric.sh "$1" "$2"
